apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app  # Updated to match your application name
  ports:
    - protocol: TCP
      port: 80       # External access port
      targetPort: 3000  # Port inside the container
      
  type: NodePort

